version: "3.8"

networks:
  vibelink:

services:
  postgres:
    build:
      context: ./database/postgSQL
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vibelink

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - vibelink

  user:
    build:
      context: ./backend/services/
      dockerfile: user/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/services/user:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - vibelink

  # swap:
  #   build:
  #     context: ./backend/services/swap/
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres
  #     - redis
  #     - cassandra
  #   volumes:
  #     - ./backend/services/swap:/usr/src/app
  #     - ./backend/uploads:/usr/src/app/uploads
  #   env_file:
  #     - .env
  #   networks:
  #     - vibelink

  redis:
    build:
      context: ./backend/utils/profile-redis
    ports:
      - "6379:6379"
    networks:
      - vibelink

  # nginx:
  #   build:
  #     context: ./backend/utils/nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./backend/uploads:/usr/share/nginx/uploads
  #   depends_on:
  #     - user
  #     - swap
  #   networks:
  #     - vibelink

  # cassandra:
  #   build:
  #     context: ./backend/utils/cassandra
  #   ports:
  #     - "9042:9042"
  #   volumes:
  #     - cassandra_data:/var/lib/cassandra
  #     - ./backend/utils/cassandra/init-scripts:/docker-entrypoint-initdb.d
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=SingleNodeCluster
  #   networks:
  #     - vibelink

volumes:
  postgres_data:
  frontend_data:
  # cassandra_data:
